### ISSUE TITLE
Uncaught Error: No search callback set!

### ISSUE THREAD

**Issue by davy79** [amitab/atom-cscope#2]
Hi,

Unfortunately I ran into an issue with the new release...
I had to update atom first and then was thrown an error that there was no search callback set...

Also: the search field of the atom-cscope pane is empty where it contained the "symbol under cursor" in the previous release if I recall correctly.

UPDATE: There is only the error when I position the cursor on a symbol and toggle the "command palette" and invoke the "find ...." command (haven't setup key bindings yet)
When I toggle the atom-cscope pane and type the symbol in the search field it works perfectly!

[Enter steps to reproduce below:]
1. place cursor on function
2. invoke "find functions calling" (same for find symbol)

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [atom-cscope](https://github.com/amitab/atom-cscope) package, v0.9.0
### Stack Trace

Uncaught Error: No search callback set!

```
At /home/jda/.atom/packages/atom-cscope/lib/views/input-view.coffee:80

Error: No search callback set!
    at InputView.module.exports.InputView.invokeSearch (/home/jda/.atom/packages/atom-cscope/lib/views/input-view.coffee:80:15)
    at Object.module.exports.AtomCscope.autoInputFromCursor (/home/jda/.atom/packages/atom-cscope/lib/atom-cscope.coffee:129:31)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-cscope:find-functions-calling (/home/jda/.atom/packages/atom-cscope/lib/atom-cscope.coffee:107:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
```
### Commands

```
     -2:49.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:49.5.0 atom-cscope:find-functions-calling (atom-text-editor.editor.vim-mode.normal-mode)
     -0:58.1.0 atom-cscope:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:57.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:56.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:56.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  6x -0:55.2.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:49.9.0 atom-ctags:rebuild (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:33 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:31.1.0 plantuml-preview:toggle (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:21.2.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:17.7.0 core:undo (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:07.2.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:02.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 atom-cscope:find-functions-calling (atom-text-editor.editor.vim-mode.insert-mode)
```
### Config

``` json
{
  "core": {
    "projectHome": "/home/jda/workspace",
    "ignoredNames": [
      ".git",
      ".odt",
      ".ods",
      ".o",
      ".a",
      "obj"
    ],
    "disabledPackages": [
      "autosave",
      "symbols-view"
    ],
    "packagesWithKeymapsDisabled": [
      "ctrl-dir-scroll"
    ]
  },
  "atom-cscope": {}
}
```
### Installed Packages

``` coffee
# User
atom-cscope, v0.9.0
atom-ctags, v4.4.1
ctrl-last-tab, v0.3.0
goto-last-edit, v0.2.2
language-plantuml, v0.1.1
language-restructuredtext, v0.10.0
last-cursor-position, v0.9.0
minimap, v4.16.2
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
pain-split, v1.4.0
plantuml-preview, v0.9.1
project-manager, v2.6.5
relative-numbers, v0.2.4
selection-highlight, v0.1.4
symbol-gen, v1.0.0
table-editor, v0.1.1
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by amitab** [comment]
@davy79 So sorry, it was a really silly thing. Although because of this I caught another bug. 
I've fixed it now. Thanks for reporting!

**Comment by davy79** [comment]
Tested and verified as working.

Thanks again for the very nice package!
